sdm660-common: releasetools: Fix android-info.txt parsing
Traceback (most recent call last):
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 86, in _run_code
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/__main__.py", line 12, in <module>
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 196, in _run_module_as_main
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 86, in _run_code
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 1648, in <module>
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 1625, in main
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/non_ab_ota.py", line 589, in GenerateNonAbOtaPackage
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/non_ab_ota.py", line 158, in WriteFullOTAPackage
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/common.py", line 2921, in FullOTA_Assertions
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/common.py", line 2915, in _DoCall
  File "/home/nobody/AOSPA/out/target/product/X01BD/obj/PACKAGING/target_files_intermediates/aospa_X01BD-target_files-eng.nobody/META/releasetools.py", line 12, in FullOTA_Assertions
    AddModemAssertion(info)
  File "/home/nobody/AOSPA/out/target/product/X01BD/obj/PACKAGING/target_files_intermediates/aospa_X01BD-target_files-eng.nobody/META/releasetools.py", line 21, in AddModemAssertion
    m = re.search(r'require\s+version-modem\s*=\s*(.+)', android_info)
  File "/home/nobody/AOSPA/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/re.py", line 200, in search
TypeError: cannot use a string pattern on a bytes-like object
ninja: build stopped: subcommand failed.

This unbreaks OTA generation.

Change-Id: I93466279b2786d9dc6265afcb0ea264707e92b05